// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateSource() {
  return window['go']['main']['App']['AuthenticateSource']();
}

export function AuthenticateTarget() {
  return window['go']['main']['App']['AuthenticateTarget']();
}

export function GetStoredCredentialsStatus() {
  return window['go']['main']['App']['GetStoredCredentialsStatus']();
}

export function SelectCredentialsFile() {
  return window['go']['main']['App']['SelectCredentialsFile']();
}
