// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateSource() {
  return window['go']['main']['App']['AuthenticateSource']();
}

export function AuthenticateTarget() {
  return window['go']['main']['App']['AuthenticateTarget']();
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetExportInfo(arg1) {
  return window['go']['main']['App']['GetExportInfo'](arg1);
}

export function GetStoredCredentialsStatus() {
  return window['go']['main']['App']['GetStoredCredentialsStatus']();
}

export function ImportData(arg1, arg2) {
  return window['go']['main']['App']['ImportData'](arg1, arg2);
}

export function SelectCredentialsFile() {
  return window['go']['main']['App']['SelectCredentialsFile']();
}
