// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateSource():Promise<string>;

export function AuthenticateTarget():Promise<string>;

export function ExportData():Promise<string>;

export function GetStoredCredentialsStatus():Promise<boolean>;

export function SelectCredentialsFile():Promise<string>;
