// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';
import {main} from '../models';

export function AuthenticateSource():Promise<string>;

export function AuthenticateTarget():Promise<string>;

export function ExportData():Promise<string>;

export function GetExportInfo(arg1:string):Promise<youtube.ExportInfo>;

export function GetStoredCredentialsStatus():Promise<boolean>;

export function ImportData(arg1:string,arg2:main.ImportOptions):Promise<string>;

export function SelectCredentialsFile():Promise<string>;
